# Generated by Django 3.1.5 on 2021-02-02 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('src', models.TextField(max_length=3000)),
                ('word', models.CharField(default='some_word', max_length=200)),
                ('pos', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['set_id', 'pos'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('max_size', models.IntegerField(default=9, null=True)),
                ('repeatable', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lgback.session')),
                ('theme_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lgback.theme')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SessionInstance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'In progress'), (3, 'Completed'), (4, 'Done')], default=1)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lgback.session')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PictureGameResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(null=True)),
                ('picture_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lgback.picture')),
                ('session_instance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lgback.session')),
                ('set_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lgback.set')),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='set_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lgback.set'),
        ),
        migrations.AddField(
            model_name='picture',
            name='theme_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lgback.theme'),
        ),
    ]
