# Generated by Django 3.1.5 on 2021-02-02 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lgback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='set_id',
            new_name='set',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='theme_name',
            new_name='theme',
        ),
        migrations.RenameField(
            model_name='picturegameresult',
            old_name='picture_id',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='picturegameresult',
            old_name='session_instance_id',
            new_name='session_instance',
        ),
        migrations.RenameField(
            model_name='picturegameresult',
            old_name='set_id',
            new_name='set',
        ),
        migrations.RenameField(
            model_name='sessioninstance',
            old_name='session_id',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='sessioninstance',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='session_id',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='theme_name',
            new_name='theme',
        ),
    ]
