# Generated by Django 3.1.5 on 2021-02-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgback', '0003_auto_20210203_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
