# Generated by Django 3.1.5 on 2021-03-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgback', '0004_session_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='src',
            field=models.TextField(),
        ),
    ]
